// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_08VxEf8f9_ncfbH9M_V0qBNoq99bts',
    appId: '1:606783957508:web:b5ba50be45433c22132351',
    messagingSenderId: '606783957508',
    projectId: 'codepie-5add8',
    authDomain: 'codepie-5add8.firebaseapp.com',
    storageBucket: 'codepie-5add8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNLITVvLKs4byT3Q4Nymnm7wSwrAaqT_4',
    appId: '1:606783957508:android:7b2eeb16683c063d132351',
    messagingSenderId: '606783957508',
    projectId: 'codepie-5add8',
    storageBucket: 'codepie-5add8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWG7_khySY5K_ILvSrFCtAXwSjESQ2mE',
    appId: '1:606783957508:ios:f0c86944b6c2f8d0132351',
    messagingSenderId: '606783957508',
    projectId: 'codepie-5add8',
    storageBucket: 'codepie-5add8.appspot.com',
    iosClientId: '606783957508-56srfdmb3mbfrsf7g87elc51v73rauqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYWG7_khySY5K_ILvSrFCtAXwSjESQ2mE',
    appId: '1:606783957508:ios:f0c86944b6c2f8d0132351',
    messagingSenderId: '606783957508',
    projectId: 'codepie-5add8',
    storageBucket: 'codepie-5add8.appspot.com',
    iosClientId: '606783957508-56srfdmb3mbfrsf7g87elc51v73rauqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloFlutter',
  );
}
